[package]
name = "superdev"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
solana-client = "2.3.2"
solana-sdk = "2.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bs58 = "0.5"
spl-token = "6.0"
spl-associated-token-account = "4.0"
base64 = "0.22"
